- Dockerfile.ubi
not supported by openshift CI (buildah)
See https://github.com/containers/buildah/issues/4325
> Dockerfile.ubi: get rid of --link flags for COPY operations

- vllm/entrypoints/grpc/grpc_server.py
fixes the following crash on startup
```
ERROR:    Traceback (most recent call last):
File "/opt/vllm/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/opt/vllm/lib/python3.11/contextlib.py", line 210, in __aenter__
return await anext(self.gen)
^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vllm/entrypoints/openai/api_server.py", line 50, in lifespan
grpc_server = await start_grpc_server(async_llm_engine, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspace/vllm/entrypoints/grpc/grpc_server.py", line 611, in start_grpc_server
await service._post_init()
File "/workspace/vllm/entrypoints/grpc/grpc_server.py", line 106, in _post_init
self.tokenizer_group = await self.engine.get_tokenizer_group() …
```
> grpc_server: fix tokenizer group usage

- Dockerfile.ubi
- get rid of --link flags for COPY operations: not supported by openshift CI (buildah)
See https://github.com/containers/buildah/issues/4325
- get rid of conda
- install ccache to leverage caching
> dockerfile cleanup

- Dockerfile.ubi
nccl, which is install> 2.18 has a bug which greatly increases memory overhead, thus a specific nccl version has to be installed
See https://github.com/NVIDIA/nccl/issues/1234 and https://github.com/vllm-project/vllm-nccl/issues/1
> Dockerfile: use fixed vllm-provided nccl version

- Dockerfile.ubi
Dockerfile.ubi: use 9.4 as base UBI tag
> bump ubi base image tag

- Dockerfile.ubi
- vllm/tgis_utils/metrics.py
> Ibm main update 2024-05-16

- Dockerfile.ubi
Building a more recent version of the vllm code with fixed `.so` from specific releases might end up breaking features if the python code contains references to features that aren't present in the downloaded wheel.
Also add the `CMAKE_BUILD_TYPE=Release` in order to build stripped and optimized wheels.
> Dockerfile.ubi: get rid of prebuilt-wheel stage

- Dockerfile.ubi
Modified the Dockerfile.ubi to add a package needed by the binary build of the cuda kernels.
> Docker.ubi: add missing package git

- Dockerfile.ubi
Shadow-utils is required by rpm and dnf. It's already in the image.
Just use it and don't remove it or it makes the image bigger.
> [CI/Build] use existing shadow-utils in Dockerfile.ubi

- Dockerfile.ubi
- add ubi Dockerfile (ibm_main 81954a7d)
- Dockerfile.ubi: remove references to grpc/protos
> add ubi dockerfile

- Dockerfile.ubi
add vllm-tgis-adapter (release: https://github.com/dtrifiro/vllm-tgis-adapter/releases/tag/0.0.1, https://pypi.org/project/vllm-tgis-adapter/)
> Dockerfile.ubi: use vllm tgis adapter

- Dockerfile.ubi
Fixed upstream in https://github.com/vllm-project/vllm/pull/5091
> Dockerfile.ubi: remove vllm-nccl workaround

- Dockerfile.ubi
- Dockerfile.ubi: only build CUDA targets from sm_75
- Dockerfile.ubi: get rid cuda-devel stage, use cuda 12.5
- Dockerfile.ubi: strip all installed libraries
- Dockerfile.ubi: remove useless installs
- Dockerfile.ubi: get rid of outdated comment
> dockerfile improvements

- Dockerfile.ubi
Reverts opendatahub-io/vllm#53
> Revert "dockerfile improvements"

- .github/workflows/sync-with-upstream.yml
this avoids triggering CI on each upstream update
> gha: sync-with-upstream workflow create PRs as draft

- Dockerfile.ubi
Includes last minutes changes to Dockerfile for tensorizer encryption and `vllm-tgis-adapter` pinning
> sync release with main

- Dockerfile.ubi
fixes [RHOAIENG-9356](https://issues.redhat.com/browse/RHOAIENG-9356)
> Dockerfile.ubi: bump vllm-tgis-adapter to 0.1.3

- Dockerfile.ubi
this is the default when `--worker-use-ray` is not provided and more than 1 GPU is available
> Dockerfile.ubi: get rid of --distributed-executor-backend=mp

- Dockerfile.ubi
https://github.com/flashinfer-ai/flashinfer/releases/tag/v0.0.9
> deps: bump flashinfer to 0.0.9

- setup.py
This PR updates `setup.py` to differentiate between the ODH and upstream vLLM projects. This work would be a prereq to making this into an independent PyPI package.
> [CI/Build] fix: update setup.py to differentiate between fork and upstream

- Dockerfile.ubi
fixup to https://github.com/opendatahub-io/vllm/pull/93, the `source=` arg was missing
> Dockerfile.ubi: properly mount .git dir

- Dockerfile.ubi
Required for vLLM 0.5.3.post1 support. See https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.2.3
> deps: bump vllm-tgis-adapter to 0.2.3

- tests/entrypoints/openai/test_completion.py
- tests/entrypoints/openai/test_serving_chat.py
- vllm/entrypoints/openai/logits_processors.py
- vllm/entrypoints/openai/protocol.py
- vllm/entrypoints/openai/serving_chat.py
- vllm/entrypoints/openai/serving_completion.py
- vllm/entrypoints/openai/serving_engine.py
Potential fix for NoneType issue in [RHOAIENG-10665](https://issues.redhat.com//browse/RHOAIENG-10665)
Issue: https://github.com/vllm-project/vllm/issues/6707
PR: https://github.com/vllm-project/vllm/pull/6954
Commit: https://github.com/vllm-project/vllm/commit/3c10591ef2e78fbb6aa341195c4b24c36ae8b84d
> [Cherry-Pick] [Bugfix] Set SamplingParams.max_tokens for OpenAI requests if not provided by user (#6954)

- Dockerfile.ubi
`requirements-adag.txt` (required for ray accelerated dag) is required as part of of `requirements-dev.txt` -> `requirements-test.txt`
> Dockerfile.ubi: add missing dependency

- Dockerfile.ubi
- deps: bump vllm-tgis-adapter to [0.3.0](https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.3.0) to include 0.5.4 fixes
- deps: bump flashinfer to 0.1.2
- Dockerfile.ubi: force using python-installed cuda runtime libraries
- Dockerfile.ubi: downgrade build-stage CUDA to 12.1 for `torch==2.4.0` compatibility 
- Dockerfile: use uv pip everywhere (it's faster)
> fix build for 0.5.4

- Dockerfile.ubi
Set `VLLM_ALLOW_LONG_MAX_MODEL_LEN=1` in the UBI docker build to have it enabled by default. This allows the operator to specify a `--max-model-len` that exceeds the value parsed from the model's `config.json`. A warning will still be printed, but the server will not crash.
See: https://github.com/vllm-project/vllm/pull/7080
> Allow long max seq length by default

- Dockerfile.ubi
- extras/smoke-test.sh
set vllm_tgis_adapter unicorn log level to warning
> Dockerfile.ubi: set uvicorn logging level

- Dockerfile.ubi
As an optimization, vLLM disables logprobs when using spec decoding by default, but this would be unexpected to users of a hosted model that happens to have spec decoding. For our usage, we want logprobs enabled by default.
See: https://github.com/vllm-project/vllm/pull/6485
Also moved setting of `PORT` env var to the adapter stage since it only works with the env var parsing in the adapter.
---
<details>
<summary><b> PR Checklist (Click to Expand) </b></summary>
<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>
<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is …
> fix: enable logprobs during spec decoding by default

- Dockerfile.ubi
This turns off tracking by default. If someone wants to, they can simply override this in yaml.
> Disable usage tracking

- Dockerfile.rocm.ubi
> ROCm build for UBI

- Dockerfile.rocm.ubi
- enable ccache for AMD builds (https://github.com/vllm-project/vllm/pull/8327)
Dockerfile.rocm.ubi:
- get rid of non-essential dependencies
- reduce image size (currently down to ~32GB from ~50GB)
- bump flash-attention to 2.6.2
- use `flash-attention` with triton backend by default:
- clone main_perf branch (waiting on https://github.com/Dao-AILab/flash-attention/pull/1203 to switch to upstream)
- build rocm target
- set up triton rocm env var
- use built triton wheel from pytorch
- configure numba, outlines and triton cache directory
- add vllm-tgis-adapter layer
https://issues.redhat.com/browse/RHOAIENG-12611
> amd build improvements

- Dockerfile.rocm.ubi
- Dockerfile.ubi
following upstream's https://github.com/vllm-project/vllm/pull/8133
> Dockerfile*.ubi: bump python to 3.12

- Dockerfile.ubi
fixup to f5387d0a8 (https://github.com/openshift/release/pull/56770)
> Dockerfile.ubi: fix PYTHON_VERSION arg usage

- Dockerfile.rocm.ubi
This sets the vllm build to a Release build type, builds libsodium,
fixes bad permissions on a logging directory, installs libsodium, and adds a LD_LIBRARY_PATH to fixup python bindings for 2 packages.
> AMD Dockerfile additions

- vllm/distributed/device_communicators/shm_broadcast.py
(cherry picked from commit 740374d456a638df98ffbc7d9dab328752330e62)
The ideal fix here is to upgrade to at least v0.5.4. In case that turns out to be not practical for some reason, I wanted to stage this backport for inclusion in the `instructlab` branch.
https://issues.redhat.com/browse/RHELAI-1211
> [core][distributed] fix zmq hang (#6759)

- Dockerfile.rocm.ubi
- Dockerfile.ubi
When git tags aren't present, `setuptools-scm` sets version to `0.1.dev`, causing the vllm-tgis-adapter layer to find an incompatible vllm version and re-install a compatible one:
```
[build]   Attempting uninstall:vllm
[build]     Found existing installation: vllm 0.1.dev1+g7f00e6e.cu124
[build]     Uninstalling vllm-0.1.dev1+g7f00e6e.cu124:
[build]       Successfully uninstalled vllm-0.1.dev1+g7f00e6e.cu124
```
By forcing installation of the correct vllm version along with the adapter, we will cause errors when this happens:
```
#33 ERROR: process "/bin/sh -c uv pip install $(echo dist/*.whl)'[tensorizer]' vllm-tgis-adapter==0.5.3" did not complete successfully: exit code: 1
------
> [vllm-grpc-adapter 1/1] RUN --mount=type=cache,target=/root/.cache/pip …
```
> Dockerfile*.ubi: install vllm and vllm-tgis-adapter in the same step to make sure the correct version is installed

- Dockerfile.hpu.ubi
Gaudi 1.18 release is based on `vllm==0.5.3.post1`. `vllm-tgis-adapter==0.5.3` on the other hand, requires `vllm>=0.6.2`, causing pip to install the latest upstream version:
```
...
2024-10-15T09:34:03.988623557Z   Attempting uninstall: vllm
2024-10-15T09:34:03.992329502Z     Found existing installation: vllm 0.5.3.post1+gaudi000
2024-10-15T09:34:04.033438958Z     Uninstalling vllm-0.5.3.post1+gaudi000:
2024-10-15T09:34:04.038142099Z       Successfully uninstalled vllm-0.5.3.post1+gaudi000
...
```
The solution is to downgrade `vllm-tgis-adapter` with the latest version compatible with `vllm==0.5.3.post1`, which is `vllm-tgis-adapter==0.2.3`
> Dockerfile.hpu: downgrade vllm-tgis-adapter to a compatible version

- Dockerfile.rocm.ubi
Not having `--mount=type=cache,target=/root/.cache/vllm` results in the `uv` cache being included in the final image.
> Dockerfile.rocm.ubi: add --mount=type=cache to final pip install

- Dockerfile.rocm.ubi
the Triton Flash Attention backend is causing crashes with ROCm 6.2 and tensor-parallel>1
> Dockerfile.rocm.ubi: use composable kernel flash attention implementation

- extras/print_gpu_memory_stats.py
- extras/smoke-test.sh
`smoke-test.sh` currently throws cuda OOM errors due to forced shutdown of vLLM, which results in leaving cuda memory allocated. We wait for a gracious shutdown and use a helper script to print out stats about gpu memory, in case similar issues arise again.
> [CI] Fix smoke tests

- Dockerfile.ubi
This PR updates the environment in the cuda image to enable torch's NCCL monitoring feature. This feature seems to be off by default, as users of our image report deadlocks lasting multiple hours before they manually delete their stuck pods. For more details on the configuration, see [here](https://pytorch.org/docs/stable/torch_nccl_environment_variables.html).
There is currently a deadlock problem in vllm, where if one tensor parallel worker dies (say due to a cuda illegal memory access while processing a request) all of the workers will be cleaned up, but the driver (which is itself also a worker) will be deadlocked waiting on an NCCL collective call that will never return. Ideally this deadlock shouldn't happen since the NCCL process groups are destroyed when the workers exit. But, …
> :wrench: Enable NCCL monitoring in cuda build

- Dockerfile.s390x
- cmake/cpu_extension.cmake
- csrc/cpu/attention.cpp
- csrc/cpu/cpu_types.hpp
- csrc/cpu/cpu_types_vxe.hpp
- csrc/cpu/quant.cpp
- requirements-cpu.txt
This PR provides CPU support for the s390x architecture. Additional PRs will add support for vllm tgis adapter (0.6.3)
To build the image for the s390x architecture:
`docker build --format docker -t vllm:v0.7.0-cpu -f Dockerfile.s390x .`
Example command to run on s390x:
`docker run -it -p 8000:8000 vllm:v0.7.0-cpu --dtype float --swap_space 1`
Tested models on s390x:
```
TinyLlama/TinyLlama-1.1B-Chat-v1.0
ibm-granite/granite-3.0-2b-instruct
ibm-granite/granite-3b-code-instruct-2k
microsoft/Phi-3-mini-4k-instruct
mistralai/Mistral-7B-v0.3
gpt-2
facebook/opt-125m
```
> adding support for s390x

- Dockerfile.s390x.ubi
Hi, this PR addresses the following issues for s390x.
1. `gcc-gfortran` package is need for installing scipy which is recently introduced in `requirements-common.txt` file.
2. Renaming `Dockerfile.s390x` to `Dockerfile.s390x.ubi` to adhere to the naming convention for ubi Docker files.
> fix: add gcc-gfortran package to dependency list

- Dockerfile.rocm.ubi
- bump ROCm to 6.3.4
- bumps`torch` to a more recent nightly, fixing FIPS issues (https://github.com/pytorch/pytorch/issues/147236)
fixes https://issues.redhat.com/browse/RHOAIENG-21197
> Dockerfile.rocm.ubi: bump ROCm to 6.3.4

- Dockerfile.ppc64le.ubi
- Dockerfile.s390x.ubi
This PR fixes docker failure for s390x.ubi that is caused by rust compiler in vllm-tgis adapter.
error:
```
[8/8] STEP 4/8: RUN --mount=type=cache,target=/root/.cache/uv     HOME=/root uv pip install "$(echo /workspace/vllm/dist/*.whl)[tensorizer]" vllm-tgis-adapter==0.6.3
Using Python 3.12.5 environment at: /opt/vllm
Resolved 136 packages in 227ms
Building hf-transfer==0.1.9
Building grpcio==1.70.0
× Failed to build `hf-transfer==0.1.9`
├─▶ The build backend returned an error
╰─▶ Call to `maturin.build_wheel` failed (exit status: 1)
[stdout]
Running `maturin pep517 build-wheel -i
/root/.cache/uv/builds-v0/.tmpkYNZ1P/bin/python --compatibility off`
[stderr]
💥 maturin failed
Caused by: Cargo metadata failed. Do you have cargo in your PATH?
Caused by: No such file or directory (os error 2) …
```
> Dockerfile.s390x: fix dependency build in vllm-tgis-adapter install
