- vllm/entrypoints/grpc/grpc_server.py
> grpc_server: return correct instance of tokenizer

- Dockerfile
- Dockerfile.ubi
- requirements-cuda.txt
- requirements-rocm.txt
- setup.py
- vllm/entrypoints/grpc/grpc_server.py
this includes ibm_main with bd23984 (ray as optional dependency) cherry-picked on top of it
> sync release with IBM/release

- vllm/entrypoints/grpc/grpc_server.py
Addendum to https://github.com/opendatahub-io/vllm/pull/36
> grpc_server: fix tokenizer group usage

- requirements-common.txt
Upgraded the requests and aiohttp depenencies. 
This PR should fix these CVE(S):
* https://www.cve.org/CVERecord?id=CVE-2024-30251
* https://www.cve.org/CVERecord?id=CVE-2024-35195
* https://www.cve.org/CVERecord?id=CVE-2023-49081
> chore(deps): update dependencies to squash snyk reported issues.

- .github/workflows/sync-with-upstream.yml
Runs nightly and creates (or updates) a PR pulling the latest changes from upstream into the main branch
> gha: add sync workflow

- Dockerfile.ubi
> Dockerfile.ubi: add missing requirements-*.txt bind mounts

- Dockerfile.ubi
- extras/custom_cache_manager.py
fixes [RHOAIENG-8043](https://issues.redhat.com//browse/RHOAIENG-8043)
Co-authored-by: Chih-Chieh-Yang <chih.chieh.yang@ibm.com>
Signed-off-by: Thomas Parnell <tpa@zurich.ibm.com>
> add triton CustomCacheManager

- Dockerfile.ubi
- get rid cuda-devel stage, use cuda 12.4
- add build flags
- remove useless installs
> Dockerfile.ubi: misc improvements

- Dockerfile.ubi
add libsodium for tensorizer encryption
> Dockerfile.ubi: use tensorizer

- .github/workflows/sync-with-upstream.yml
Fixes failing nightly workflow
> gha: fix fetch step in upstream sync workflow

- .github/workflows/sync-with-upstream.yml
- Dockerfile.ubi
Fixes https://issues.redhat.com/browse/RHOAIENG-9356
> sync release with main

- Dockerfile.ubi
https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.2.0
> pin adapter to 0.2.0

- setup.py
Reverts opendatahub-io/vllm#95
> Revert "[CI/Build] fix: update setup.py to differentiate between fork and upstream"

- setup.py
Followup from #95
The above PR differentiate the `main` branch of this repo from the upstream vLLM project, but after talking with @n1hility we may want to package the `instructlab` branch of this repo specifically.
This PR would precede that - it's worth having a larger discussion as to our packaging strategy, but merging this will allow us to build from either branch depending on the direction we decide to go.
---
<details>
<summary><b> PR Checklist (Click to Expand) </b></summary>
<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>
<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be …
>  [CI/Build] fix: update setup.py to differentiate between main and instructlab

- Dockerfile.ubi
[changelog for 0.4.0](https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.4.0)
https://issues.redhat.com/browse/RHOAIENG-11591
> deps: bump vllm-tgis-adapter to 0.4.0

- Dockerfile.ubi
A review showed that nowhere in the Dockerfile.ubi do we do a microdnf -y update to pickup any known CVE and bugfixes. This patch adds this to the build process.
FILL IN THE PR DESCRIPTION HERE
FIX #xxxx (*link existing issues this PR will resolve*)
**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**
---
<details>
<summary><b> PR Checklist (Click to Expand) </b></summary>
<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>
<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. …
> Start by updating the image

- Dockerfile.rocm.ubi
- Dockerfile.ubi
Changelog: https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.5.0
> bump tgis adapter to v0.5.0

- Dockerfile.ubi
> Dockerfile.ubi: remove adag dependency

- Dockerfile.rocm.ubi
- Dockerfile.ubi
Changelog https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.5.1
> bump tgis adapter to v0.5.1

- Dockerfile.rocm.ubi
FILL IN THE PR DESCRIPTION HERE
FIX #xxxx (*link existing issues this PR will resolve*)
**BEFORE SUBMITTING, PLEASE READ THE CHECKLIST BELOW AND FILL IN THE DESCRIPTION ABOVE**
---
<details>
<summary><b> PR Checklist (Click to Expand) </b></summary>
<p>Thank you for your contribution to vLLM! Before submitting the pull request, please ensure the PR meets the following criteria. This helps vLLM maintain the code quality and improve the efficiency of the review process.</p>
<h3>PR Title and Classification</h3>
<p>Only specific types of PRs will be reviewed. The PR title is prefixed appropriately to indicate the type of change. Please use one of the following:</p>
<ul>
<li><code>[Bugfix]</code> for bug fixes.</li>
<li><code>[CI/Build]</code> for build or continuous integration …
> Retrigger build

- Dockerfile.rocm.ubi
- Dockerfile.ubi
Has changes for loading catikit style *.pt adapters
> bump adapter to 0.5.2

- Dockerfile.rocm.ubi
- Dockerfile.ubi
> bump adapter to 0.5.3

- vllm/OWNERS.txt
> Add owners file

- Dockerfile.rocm.ubi
- slim down final image
- use BASE_UBI_IMAGE_TAG in AMD repo URL
- make sure the venv's torch libraries are available
> Dockerfile.rocm.ubi: misc improvements

- Dockerfile.rocm.ubi
- Dockerfile.ubi
Changelog: https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.6.0
> deps: bump vllm-tgis-adapter to 0.6.0

- Dockerfile.rocm.ubi
- Dockerfile.ubi
Changelog:
- https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.6.2
- https://github.com/opendatahub-io/vllm-tgis-adapter/releases/tag/0.6.1
> deps: bump vllm-tgis-adapter to 0.6.2

- .buildkite/test-pipeline.yaml
- docs/source/serving/openai_compatible_server.md
- examples/online_serving/openai_transcription_client.py
- requirements-common.txt
- requirements-test.in
- requirements-test.txt
- tests/entrypoints/openai/correctness/test_lmeval.py
- tests/entrypoints/openai/correctness/test_transcription_api_correctness.py
- tests/entrypoints/openai/test_basic.py
- tests/entrypoints/openai/test_transcription_validation.py
- tests/test_config.py
- vllm/assets/audio.py
- vllm/config.py
- vllm/entrypoints/openai/api_server.py
- vllm/entrypoints/openai/protocol.py
- vllm/entrypoints/openai/serving_engine.py
- vllm/entrypoints/openai/serving_transcription.py
- vllm/model_executor/models/interfaces.py
- vllm/model_executor/models/registry.py
- vllm/model_executor/models/whisper.py
- [Frontend] Add `/v1/audio/transcriptions` OpenAI API endpoint (https://github.com/vllm-project/vllm/pull/12909)
- [Bugfix] Missing Content Type returns 500 Internal Server Error (https://github.com/vllm-project/vllm/pull/13193)
> [cherry-pick] add whisper OpenAI API endpoint

- Dockerfile.rocm.ubi
- Dockerfile.ubi
> deps: bump vllm-tgis-adapter to 0.6.3

- Dockerfile.rocm.ubi
- Dockerfile.s390x.ubi
- Dockerfile.ubi
We don't need them and it creates extra files that may be picked up in container scans...
> fix: don't install docs with system packages

- Dockerfile.ppc64le.ubi
Updated the dockerfile to build numactl and lapack from source which was getting pulled from rhel-9 repos
> update: building numactl and lapack from source

- Dockerfile.s390x.ubi
This PR fixes build of hf-transfer pip package. Added perl-core dependency which is needed to build hf-transfer. Also updated rust environment variable.
> fix: fixed rust env variables and install perl-core dependency

- Dockerfile.rocm.ubi
https://issues.redhat.com/browse/INFERENG-375
> Dockerfile.rocm.ubi: add [audio,video,tensorizer] extras to vllm install
